---
kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: bdebyl/yamllint
      auto_tag: true

