---
kind: pipeline
name: default

steps:
  - name: gate-master
    image: bdebyl/alpine-git
    commands:
      - git fetch origin +refs/heads/master
      - git show-ref
      - git diff --name-only HEAD~1..HEAD | grep Dockerfile || exit 78
    when:
      branch:
        - master

  - name: gate-pr
    image: bdebyl/alpine-git
    commands:
      - git fetch origin +refs/heads/master
      - git show-ref
      - git diff --name-only $(git merge-base refs/remotes/origin/master HEAD)..HEAD | grep Dockerfile || exit 78
    when:
      branch:
        exclude:
          - master

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: bdebyl/yamllint
    when:
      branch:
        - master
---
kind: signature
hmac: 4cfd358a462cbfae4c484efa6a6948ea9e3f8a20d24ec0824e74476a5c400a4c

...
