---
kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
  - name: gate
    image: bdebyl/alpine-git
    commands:
      - git fetch origin +refs/head/master
      - git show-ref
      - git diff --name-only $(git merge-base refs/remotes/origin/master HEAD)..HEAD | grep Dockerfile || exit 78

  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: bdebyl/yamllint
      auto_tag: true

